### ISSUE TITLE
Not able to render Push Template PN

### ISSUE THREAD

**Issue by aman-agarwal15** [CleverTap/PushTemplates#18]
Hi guys.

I am not able to work with the Push Template SDK, template PNs are not rendered (normal CT PNs are working fine, however) with the following message in the logs
> Logs: Couldn't render notification: the bind value at index 1 is null

It seems `wzrk_pid` is coming as null

Intent Extras Received:
> {wzrk_acct_id="test account id here", pt_big_img="valid image link here", pt_ico="valid image link here", pt_msg=Test Message, nm=nm, nt=nm, pr=, pt_bg=#EFEEE1, pt_id=pt_basic, pt_title=Test title, wzrk_pivot=wzrk_default, wzrk_cid=Alerts, wzrk_rnv=true, wzrk_ttl=1592625399, wzrk_push_amp=false, wzrk_bc=, wzrk_bi=2, wzrk_dt=FIREBASE, wzrk_id=0_0, wzrk_pn=true}

Note: I am custom handling the Push Notifications

**Comment by darshanclevertap** [comment]
Hi @aman-agarwal15 

Thanks for raising our first GitHub issue and we're sorry for the inconvenience caused to you. 

Our SDK doesn't handle the absence of `wzrk_pid` key. This happens only when you're trying to send a "test" Push Notification via the Profile page on the CleverTap dashboard. 

I can assure you this won't happen when you run the Push campaign, you can test this by creating campaign in your TEST account or a campaign just for yourself to see how it works. This is because a Push Campaign will always have the `wzrk_pid` key present.

We're aware of this issue internally and have already fixed it for the upcoming v0.0.3 release.

Hope this helps!

**Comment by aman-agarwal15** [comment]
@darshanclevertap Thanks for the quickest response ever :).

Yeah, I ran a push campaign on our test dashboard and it seems to be working fine. Thanks for the help. May I know when is the next release planned?

**Comment by darshanclevertap** [comment]
@aman-agarwal15 it's in the QA and final touches phase. We're aiming for the end of next week. I'd suggest you "watch" this repo for the quickest updates on releases. :)

**Comment by aman-agarwal15** [comment]
@darshanclevertap I hope this issue is fixed in `0.0.3`?

**Comment by darshanclevertap** [comment]
Yes @aman-agarwal15 this is fixed in 0.0.3

**Comment by knowamit** [comment]
Hi I am version 0.0.8

still its not rendering also not showing any error while debugging the App 

`template Bundle[{wzrk_acct_id=658-969-855Z, pt_msg_summary=Again Some Dummy Text, pt_msg=Free, pt_sl1=https://nojoto.com/leaderboard, pt_img1=https://nojoto.com/resources/images/smiley_love.png, pt_img2=https://nojoto.com/resources/images/smiley_love.png, pt_img3=https://nojoto.com/resources/images/smiley_love.png, nm=Only on TestTrack, nt=A Cool Notification Being Tested!!, pr=max, pt_id=pt_carousel, pt_title=A Carousal it is!, pt_small_img=https://nojoto.com/resources/images/smiley_love.png, wzrk_pivot=wzrk_default, wzrk_ttl_s=86400, wzrk_cid=NJT, wzrk_pid=1644394588, wzrk_rnv=true, wzrk_ttl=1644481511, wzrk_push_amp=false, wzrk_bc=, wzrk_bi=2, wzrk_ck=1644394588, wzrk_dt=FIREBASE, wzrk_id=1644394588_20220209, wzrk_pn=true}]`

**Comment by darshanclevertap** [comment]
@knowamit The library is now a part of the [CleverTap Android SDK](https://github.com/CleverTap/clevertap-android-sdk) Github repo.

[Please checkout the integration steps here for the stable release v1.0.0 and above.](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTPUSHTEMPLATES.md)
