### ISSUE TITLE
Feature request to support formatted pt_json 

### ISSUE THREAD

**Issue by mwshubham** [CleverTap/PushTemplates#36]
Thank you @darshanclevertap and clevertap team for this wonderful lib push templates. 
Can we support formatted pt_json as well e.g.

{
  "pt_title": "pt_title",
  "pt_msg": "pt_msg",
  "pt_img1": "",
  "pt_img2": "",
  "pt_img3": "",
  "pt_small_img": "",
  "pt_msg_summary": "pt_msg_summary",
  "pt_dl1": "",
  "pt_bg": "#ffffff"
}

For now we are getting json exception in Utils.fromJson(new JSONObject(pt_json))

**Comment by darshanclevertap** [comment]
@mwshubham So the Push Templates SDK expects a minified JSON. Our dashboard doesn't have the ability to minify a formatted JSON. For now, I'd recommend you use minified JSON via my favourite [JSON Formatter website](https://jsonformatter.org/) when you enter it on the dashboard. I'll take this up as an enhancement on the CleverTap dashboard side 👍

**Comment by mwshubham** [comment]
Thanks for the quick response and for taking the feature request for the dashboard.
