### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by mwshubham** [CleverTap/PushTemplates#37]
Documentation:
There might be a requirement of updating documentation
e.g. For pt_carousel, at least 3 Images are required. But as per the documentation, it is only 2. 

Feature Request:
Validation on the dashboard for different push templates. e.g. if there is any required field missing/incorrect, can we have the same prompted on the Dashboard itself.

**Comment by darshanclevertap** [comment]
@mwshubham Thank you for pointing out the discrepancy in the documentation. We will fix that.

As for the dashboard validation, we've raised it with our product team and we'll get back to you once we have some concrete timelines.
