### ISSUE TITLE
Not able to build with 0.0.5 version

### ISSUE THREAD

**Issue by abhinav422** [CleverTap/PushTemplates#41]
Since the dependency of exoplayer has changed from 'compileOnly' to 'implementation', it gives following build error

AAPT: error: attribute auto_show not found
AAPT: error: attribute controller_layout_id not found
AAPT: error: attribute show_buffering not found

Was working fine in 0.0.4 version

**Comment by darshanclevertap** [comment]
@abhinav422 Are you shrinking resources or using proguard to remove Exoplayer dependencies in your app?

**Comment by abhinav422** [comment]
@darshanclevertap we use proguard for release variant, but currently am building with debug variant with no proguard or shrink resources

**Comment by darshanclevertap** [comment]
@abhinav422 Can you list the dependencies you're using in your `build.gradle`? We'll try to reproduce this on our end as well

**Comment by abhinav422** [comment]
@darshanclevertap we have actually a lot of dependencies, was working fine in 0.0.4, it is working fine in 0.0.5 when I add exoplayer dependency explicitly, but currently i dont want to add that

**Comment by darshanclevertap** [comment]
@abhinav422 Exoplayer is an `implementation` dependency for the PushTemplates SDK, it should ideally get added to your project at build time. Could you invalidate your Gradle caches and try building the app once again?

**Comment by abhinav422** [comment]
@darshanclevertap i have tried invalidating caches and deleting gradle caches, I tried creating a new project and add dependency there as well, but its giving the same error

**Comment by darshanclevertap** [comment]
@abhinav422 We'll try to reproduce this on our end. But without the ExoPlayer dependency, you'll not be able to use the SDK as we have made it mandatory for now. I'd suggest you consider using Exoplayer and reap the benefits of using the Video Push Template.

**Comment by abhinav422** [comment]
@darshanclevertap Would be great if there was support for clevertap4.0.0 in push-template0.0.4, since the latter was building fr me

**Comment by darshanclevertap** [comment]
@abhinav422 In v0.0.6, we've removed the ExoPlayer dependency and Video Template. Let us know if you face any issues with that.
