### ISSUE TITLE
Some templates are not rendered

### ISSUE THREAD

**Issue by aman-agarwal15** [CleverTap/PushTemplates#43]
Hi Team, it seems for some templates there is no check for the deep-link list size in the `TemplateRenderer.java` file. Hence, even though deep-link is not mandatory according to the documentation, we have to pass it anyway as the execution enters the `if` block, where the code tries to get the 0th position value from the empty list, and the `IndexOutOfBoundsException`, is thrown and the execution stops, and the notification is not rendered at all.

Attaching a screenshot as an example from `0.0.6`'s code (input box template)

![image](https://user-images.githubusercontent.com/52480970/106245830-27789480-6233-11eb-97f9-ef7c8a266740.png)

**Comment by darshanclevertap** [comment]
@aman-agarwal15 Yes we know about this issue and we'll be fixing this in the next version. 

For now, you can pass one deep-link to the key - `pt_dl1` and ensure that your Push Notifications do render on the device.

**Comment by mwshubham** [comment]
Fixed in https://github.com/CleverTap/PushTemplates/pull/47

**Comment by mwshubham** [comment]
@darshanclevertap Please mark this close as it is fixed in https://github.com/CleverTap/PushTemplates/pull/48
