### ISSUE TITLE
Possibly Missing Break Statement

### ISSUE THREAD

**Issue by mwshubham** [CleverTap/PushTemplates#45]
https://github.com/CleverTap/PushTemplates/blob/6eca9ffc01183bfb033ac1ee1d2d0befdcea73ed/pushtemplates/src/main/java/com/clevertap/pushtemplates/TemplateRenderer.java#L305

**Comment by darshanclevertap** [comment]
@mwshubham You can fork out a branch and send in a PR for this issue and #46 if you want. We'd love to get some contributions to this project 👍🏾

**Comment by mwshubham** [comment]
@darshanclevertap Closing this issue as it fixed in https://github.com/CleverTap/PushTemplates/pull/48
