### ISSUE TITLE
Incorrect field for Zero Bezel

### ISSUE THREAD

**Issue by SushantCT** [CleverTap/PushTemplates#51]
Under the Zero bezel template - currently deep link is shown as optional - but post testing I have checked and confirmed that deep link is a MANDATORY FIELD and the notification renders only once you add that.

**Comment by darshanclevertap** [comment]
@SushantCT Thanks for pointing this out. That is indeed the case. We will update our documentation.

**Comment by darshanclevertap** [comment]
This has been fixed.
