### ISSUE TITLE
Timer notification issue

### ISSUE THREAD

**Issue by verticalakash** [CleverTap/PushTemplates#55]
Image get trimmed from bottom in case of pt_big_img_alt provided
![WhatsApp Image 2022-01-21 at 11 53 25 AM](https://user-images.githubusercontent.com/18140593/150476979-13b29ce0-c778-4f62-8af7-b7bb45a455c0.jpeg)
.

**Comment by darshanclevertap** [comment]
@verticalakash Which version of the SDK are you using?

**Comment by verticalakash** [comment]
@darshanclevertap  implementation 'com.clevertap.android:clevertap-android-sdk:4.2.0'
    implementation 'com.clevertap.android:push-templates:0.0.8'

**Comment by darshanclevertap** [comment]
@verticalakash we have released a stable version v1.0.0, where we have fixed a lot of image and text issues. Please find the integration [documentation for it here](https://developer.clevertap.com/docs/push-templates-android)

Please try the stable version and let us know if the issue persists. Please note the stable version v1.0.0 is compatible with CleverTap Android SDK v4.4.0 only, so you will have to update our core SDK as well.

**Comment by verticalakash** [comment]
@darshanclevertap Text issue is fixed in latest version but image is cutting from top and bottom.

**Comment by darshanclevertap** [comment]
@verticalakash can you share a screenshot and the image URL if possible?

**Comment by darshanclevertap** [comment]
@verticalakash can you open a new issue on the CleverTap Android SDK github repo so that we can track it properly.
