### ISSUE TITLE
Message is getting cut in notification tray

### ISSUE THREAD

**Issue by verticalakash** [CleverTap/PushTemplates#56]
Message is getting cut when notification is delivered with notification tray closed. It should be ellipsized from end.
![Custom_push_carousel_delivery-20220110-061614](https://user-images.githubusercontent.com/18140593/150477408-bdf5a3bf-9edd-4cfe-8b25-f3db04e7c295.jpeg)

**Comment by darshanclevertap** [comment]
@verticalakash The library is now a part of the [CleverTap Android SDK](https://github.com/CleverTap/clevertap-android-sdk) Github repo.

[Please checkout the integration steps here for the stable release v1.0.0 and above.](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTPUSHTEMPLATES.md)

If the issue persists, please open a new issue on that repo. Thanks!
