### ISSUE TITLE
Auto Carousel Not Working

### ISSUE THREAD

**Issue by rahulr4** [CleverTap/PushTemplates#57]
Hi,

I was integrating auto carousel template push and i have added all the required keys mentioned in the doc.
I have also gone through the Template Render Class renderAutoCarouselNotification() method and I can see that you are downloading all the images in a loop and setting it in the R.id.fimg Imageview but i don't see anywhere the code where you are actually doing the carousel behavior.

Also the push notification doesnt event show the images in the notification bar

**Comment by rahulr4** [comment]
![clevertap_issue](https://user-images.githubusercontent.com/3830891/150644496-a718ef62-a114-43bc-92e3-b84bac27ba5c.png)

Recording Notification Viewed event for notification:  Bundle[{wzrk_acct_id=48K-44K-5R5Z, pt_dl1=dineout://s?t=Dineout Pay, pt_ico=https://img.apkgit.com/b1/com.dineout.book/9.9.4/icon.png, pt_msg=On your tips, pt_img1=https://image.shutterstock.com/image-photo/raw-salmon-fillet-cooking-ingredients-260nw-274746884.jpg, pt_img2=https://image.shutterstock.com/image-photo/food-background-banner-website-selection-260nw-1753925045.jpg, pt_img3=https://im1.dineout.co.in/images/uploads/deals/41140/q/q/6a803de0fede8b7a207e3c498f7a0d3e.jpg, nm=...in your Dineout wallet! Tap to use it now & save more on your bills via Dineout Pay. Take precautions, stay safe!, nt=You have ₹100+ unused PromoCash..., pr=, ico=https://st1.dineout-cdn.co.in/images/uploads/mailer/2019/Oct/17/dineout-logo.png, pt_bg=#1AFF0000, pt_id=pt_carousel, pt_title=Best of 2021, pt_summary=Get best offers!, wzrk_pivot=wzrk_default, wzrk_cid=default, wzrk_clr=#f1645b, wzrk_rnv=true, wzrk_ttl=1642951052, wzrk_push_amp=false, wzrk_bc=, wzrk_bi=2, wzrk_ck=1525344384_1642864652, wzrk_dl=dineout://s?t=Dineout Pay, wzrk_dt=FIREBASE, wzrk_id=0_0, wzrk_pn=true, wzrk_st=Hello World!}]

All the required parameters i am sending but as you can see no carousal image is shown. I have debugged also but it is not rendering

**Comment by darshanclevertap** [comment]
@rahulr4 The library is now a part of the [CleverTap Android SDK](https://github.com/CleverTap/clevertap-android-sdk) Github repo.

[Please checkout the integration steps here for the stable release v1.0.0 and above.](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTPUSHTEMPLATES.md)

If the issue persists, please open a new issue on that repo. Thanks!
