### ISSUE TITLE
Timer template with "pt_big_img" not delivering to device

### ISSUE THREAD

**Issue by MahaleTushar** [CleverTap/PushTemplates#58]
Timer template with "pt_big_img" value is not getting delivered on Android devices.

If we use timer template without image it's working fine.
cleverTapSdkVersion 5.1.0
cleverTapTemplateVersion 1.1.0

**Comment by darshanclevertap** [comment]
@tusr this project is no longer maintained and the [Push Templates SDK](https://github.com/CleverTap/clevertap-android-sdk/tree/master/clevertap-pushtemplates) has been made a part of the [CleverTap Android SDK](https://github.com/CleverTap/clevertap-android-sdk)
Please raise the issue [here](https://github.com/CleverTap/clevertap-android-sdk/issues/new/choose) with the above information and screenshots if possible.
