### ISSUE TITLE
Push Template Gradle File is not updated

### ISSUE THREAD

**Issue by ravirajjak** [CleverTap/PushTemplates#59]
I request to the tech team to push the latest changes which is version 1.0.9. My project is not getting compiled due to this version update even though i am targeting SDK 33

**Comment by darshanclevertap** [comment]
@ravirajjak what is the error that you are getting? Can you share the error logs or a screenshot?

**Comment by darshanclevertap** [comment]
@ravirajjak This SDK repo has been moved to the Core CleverTap Android SDK. Please find the details here -> https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTPUSHTEMPLATES.md
