### ISSUE TITLE
pt_rating exception

### ISSUE THREAD

**Issue by ravirajjak** [CleverTap/PushTemplates#60]
issue: Exception: Unterminated object at character 46 of {wzrk_acct_id=TEST-986-87Z-R56Z, pt_dl1=https://app.adjust.net.in, pt_msg=description, nm=template, nt=rating, pr=, pt_bg=#FFFFFF, pt_id=pt_rating, pt_title=test, wzrk_pivot=wzrk_default, pt_default_dl=https://app.adjust.net.in, wzrk_cid=coin_channel, wzrk_rnv=true, wzrk_ttl=1698904700, wzrk_push_amp=false, wzrk_bc=, wzrk_bi=2, wzrk_ck=818300448, wzrk_dt=FIREBASE, wzrk_id=0_0, wzrk_pn=true}

Unable to receive the notification of rating

**Comment by darshanclevertap** [comment]
@ravirajjak this repo is deprecated. Please checkout the following repo where Push Templates has been moved to -> https://github.com/CleverTap/clevertap-android-sdk

Please follow the new Push Templates SDK documentation -> https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTPUSHTEMPLATES.md

If you still have a query please raise an issue here -> https://github.com/CleverTap/clevertap-android-sdk/issues/new/choose
